// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD95-WsUbvJ-i0NVJGq43sp8GbXuN_drvQ',
    appId: '1:333805316478:web:0cebcc0b407a88d79d2b2f',
    messagingSenderId: '333805316478',
    projectId: 'smartfocus-f0db1',
    authDomain: 'smartfocus-f0db1.firebaseapp.com',
    storageBucket: 'smartfocus-f0db1.firebasestorage.app',
    measurementId: 'G-88BJ39JFZX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgizmL9gUWhvunQzi_8SSF4Og8k_Q5rhw',
    appId: '1:333805316478:android:52967ac2982387da9d2b2f',
    messagingSenderId: '333805316478',
    projectId: 'smartfocus-f0db1',
    storageBucket: 'smartfocus-f0db1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRiHHPYiGviQzZi-ycsy2HaydJIFZGUnE',
    appId: '1:333805316478:ios:46499deb7e93b52f9d2b2f',
    messagingSenderId: '333805316478',
    projectId: 'smartfocus-f0db1',
    storageBucket: 'smartfocus-f0db1.firebasestorage.app',
    iosBundleId: 'com.example.smartlock',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRiHHPYiGviQzZi-ycsy2HaydJIFZGUnE',
    appId: '1:333805316478:ios:46499deb7e93b52f9d2b2f',
    messagingSenderId: '333805316478',
    projectId: 'smartfocus-f0db1',
    storageBucket: 'smartfocus-f0db1.firebasestorage.app',
    iosBundleId: 'com.example.smartlock',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD95-WsUbvJ-i0NVJGq43sp8GbXuN_drvQ',
    appId: '1:333805316478:web:0e7f52d415ce0d4f9d2b2f',
    messagingSenderId: '333805316478',
    projectId: 'smartfocus-f0db1',
    authDomain: 'smartfocus-f0db1.firebaseapp.com',
    storageBucket: 'smartfocus-f0db1.firebasestorage.app',
    measurementId: 'G-TPX06Z6XQF',
  );
}
